server:
  port: 8084
spring:
  application:
    name: exam-file
  datasource:
    url: jdbc:mysql://localhost:3306/wk_school?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  file-storage: #文件存储配置
    default-platform: local-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如.min.jpg或.png等
    local: # 本地存储，不使用的情况下可以不写
      - platform: local-1 # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: true #启用访问（线上环境建议用 Nginx 静态资源服务）
        domain: "" # 访问域名，例如http://127.0.0.1:8030/test/file/，注意后面要带上path-patterns前缀，且不要忘了"/"
        base-path: D:/Temp/test/ # 存储路径
        path-patterns: /test/file/** # 访问路径，开启enable-access后，通过此路径可以访问到上传的文件
